export interface MatchDetailModel{
    nameEvent:string,
    resultEvent: string,
    ShootsOnGoalHome: number,
    ShootsOnGoalAway: number,
    ShootsOffGoalHome: number,
    ShootsOffGoalAway: number,
    CornerKicksHome: number,
    CornerKicksAway: number,
    FoulsHome: number,
    FoulsAway: number,
    YellowCardsHome: number,
    YellowCardsAway: number,
    RedCardsHome: number,
    RedCardsAway: number,
}